### ISSUE TITLE
Can't get to compile on os x (9.4.1)

### ISSUE THREAD

**Issue by bnolan** [samdauwe/BabylonCpp#8]
The current version of xcode only has `std::optional` under `experimental`. I changed the imports to `#include <experimental/optional>` but now I get errors because I think `std::optional` changed when it was no longer experimental. I'm not sure if I should try and:

* Fix babyloncpp to work with `experimental/optional`
* Install xcode 10 (beta version)
* Use a boost version of optional

Any ideas?

**Comment by bnolan** [comment]
This error is caused by differences between std::optional and std::experimental::optional.

```
.../BabylonCpp/src/BabylonCpp/src/audio/weighted_sound.cpp:135:21: error: no member named 'has_value' in
      'std::experimental::fundamentals_v1::optional<unsigned long>'
  if (_currentIndex.has_value() && *_currentIndex < _sounds.size()) {
```

**Comment by bnolan** [comment]
Okay - used `optional` [from here](https://github.com/youknowone/xcode-libcxx) and the compile has gotten a bit further.

**Comment by bnolan** [comment]
Ok it compiles and runs - but I just get a blue screen. You can change the clear color with `scene->clearColor` and it changes the color, but for some reason no geometry is rendering. No error messages on the command line.

![screen shot 2018-09-10 at 11 32 28 am](https://user-images.githubusercontent.com/17499/45270107-66381380-b4ed-11e8-9816-2980819f75a1.png)

Had to change the glfw hints as so:

```
      glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
      glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
      glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_NATIVE_CONTEXT_API);
      glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
      glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
```

**Comment by bnolan** [comment]
Okay - got logging writing out to `std::cout` and got this:

```
ganymede:BabylonCpp$ ./release_build/build/bin/SampleLauncher -S CuboidScene --inspector
gl 3.3
Setting hint
[2018-09-11 13:34:38.490] [ INFO] [GLRenderingContext::initialize] | Using GL version: 4.1 ATI-1.68.20
[2018-09-11 13:34:38.490] [ INFO] [Engine::Engine] | BabylonCpp engine (v3.3.0) launched
[2018-09-11 13:34:38.724] [ERROR] [Engine::CompileRawShader] | ERROR: 0:1: '' :  version '300' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:312: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140
```

**Comment by bnolan** [comment]
Victory! The inspector still flashes red, but the cuboid renders. I changed `#version 300 es` to `#version 330`.

![screen shot 2018-09-11 at 1 43 58 pm](https://user-images.githubusercontent.com/17499/45333159-c3ed5e00-b5c8-11e8-9f89-2acba7cd1deb.png)

**Comment by bnolan** [comment]
Works great! 
![screen shot 2018-09-11 at 1 48 35 pm](https://user-images.githubusercontent.com/17499/45333274-6efe1780-b5c9-11e8-86b1-67402ed7d6ec.png)

**Comment by samdauwe** [comment]
That is good news! So, you updated the shader code by replacing #version 300 es to #version 330 just before compilation?

That last screenshot you shared seems tot have an issue with the lighting. Do you see any issues with other samples?

**Comment by samdauwe** [comment]
Logging without the inspector can be enabled as follows:

./SampleLauncher --sample=CuboidScene --verbose
